### PR TITLE
Images

### PR DESCRIPTION
**Pull request by Spicy-Axolotl**
There might a few hidden bugs, don't know.

### CODE REVIEW

**Comment by Spicy-Axolotl** [comment]
I'll fix any bugs I find later.

**Comment by Hexasphere0** [comment]
Stuff that needs images

- [x] Microsoft
- [x] Jeff bezos
- [ ] Forks
- [x] Atricos
- [x] All the purple cubes

**Comment by Spicy-Axolotl** [comment]
You're gonna need to help me with the purple cubes.

**Comment by Hexasphere0** [comment]
Added all the profile pictures most of the purple cubes are gone

**Comment by Hexasphere0** [comment]
Variables now show their images properly and hidden names dont show up

**Review by Hexasphere0 — APPROVED** [review]

**Pull request merged**
